### ISSUE TITLE
Impossible to change run parameters using Docker installation ?

### ISSUE THREAD

**Issue by remylegoff** [champost/DECX#4]
The docker installation works well using the dummy files to test the installation but it raises one problem. It's not possible to access the file to change the run parameters (number of iteration, stoppingprecision, ...). We can have, for example, this kind of message :
`Attained the maximum number of iterations: 1000                                                                         Please rerun Lagrange having increased the maximum number of iterations                                                 or reduce the "stoppingprecision" (currently at 0.0001) of the optimisation step`
And there's no documentation on a file that could modify that. How can I modify the run parameters ?
@iago-lito

**Comment by champost** [comment]
Hi @remylegoff, thank you for reporting your issue. The installation process of DECX has lately been revamped with the help of @iago-lito. Unfortunately, I haven't been following this closely. 

@iago-lito : any insight into @remylegoff's installation troubles ?

**Comment by iago-lito** [comment]
Hi @remylegoff and sorry for the silence, I'll be back from vacations next week :)

It seems that the installation process with docker went well on your machine, and that you are hitting another issue here: the project has no thorough documentation yet, and I'm not 100% confident that all parameters like `stoppingprecision` or the maximum number of iterations can be tweaked with the configuration file yet.

I'm working with [Fabien Condamine](https://isem-evolution.fr/membre/condamine/), who is familiar with the usage of DECX, and we plan on writing such a documentation this summer. For now, I can only suggest that you get in touch with him to get feedback about the specific kind of errors DECX is showing in your situation. He can also provide various examples of working files.

Do you guys already know each other btw?

**Comment by iago-lito** [comment]
Closing as Fabien tells me that it's working now on your side. Don't hesitate to reopen in case the problem happens again :)
